### ISSUE TITLE
istio smartDNS unsupport

### ISSUE THREAD

**Issue by jingslunt** [alibaba/kt-connect#329]
- istio smartDNS:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-auto
spec:
  hosts:
  - auto.internal
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 198.51.100.2
```

- command1:
```
curl -ik https://kubernetes.default
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache, private
Content-Type: application/json
Date: Mon, 20 Jun 2022 05:21:36 GMT
Content-Length: 165

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```
- command2:
```
curl auto.internal
curl: (6) Could not resolve host: auto.internal

```
