### ISSUE TITLE
启动 ktctl 成功后，可以根据IP访问k8s集群中的 pod。但是无法访问 service 。

### ISSUE THREAD

**Issue by thousmile** [alibaba/kt-connect#430]
这是启动 ktctl connect 成功的截图

![QQ截图20230505154953](https://user-images.githubusercontent.com/28520524/236404190-7fffc9e9-8d3c-4b4f-9a2e-5242d4a98555.png)

通过 pod ip 可以访问成功  （黄色部分）
通过 Ingress 反向代理也是可以访问

<span style="color: red"> 但是通过 service 的 IP 或者  名称。无法访问。（红色部分）</span>

![QQ截图20230505154910](https://user-images.githubusercontent.com/28520524/236404325-3796d71c-22fb-48ae-b5cf-c2a917054325.png)

在k8s集群中，任意一个pod中也是可以通过 service 的 IP 或者  名称 访问
![QQ截图20230505154731](https://user-images.githubusercontent.com/28520524/236405638-dcc02972-fcca-431f-9fcd-a43b580ce559.png)

下面是k8s部署的yaml

```yaml
################## hello deployment ##################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.24.0
          ports:
            - containerPort: 80


---
################## hello Service ##################
apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
  labels:
    app: hello-nginx
spec:
  type: ClusterIP
  selector:
    app: hello-nginx
  ports:
    - port: 80
      targetPort: 80

---
################## ingress myapp ##################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-nginx
  labels:
    app: hello-nginx
spec:
  ingressClassName: nginx
  rules:
    - host: hello.example.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: hello-nginx
                port:
                  number: 80
```
