### ISSUE TITLE
这个项目团队还在么？怎么快1年没更新版本了，如何解决springcloud服务间访问流量转发的问题？

### ISSUE THREAD

**Issue by 982186883** [alibaba/kt-connect#451]
springcloud开发中，对于服务间访问如何讲流量转发到本地项目上？毕竟服务间的访问并没有通过svc，而是直接在注册中心中获取的各个Pod的地址，然后进行负载均衡调用的请求，像这样的请求如何讲流浪转发到本地项目中呢？

**Comment by Jevai** [comment]
```
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      server-addr: ${NACOS_HOST:lcdp-register}:${NACOS_PORT:8848}
      discovery:
        namespace: @nacos.namespace.id@
        ip: ${spring.application.name}-${profiles.active}
      config:
        namespace: @nacos.namespace.id@
``` 
修改IP配置，让它注册内部域名而不是IP
